source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!


target 'Example' do

    pod 'TweeningUIPageViewController', :git => 'https://github.com/adamszeremeta/TweeningUIPageViewController.git'

end
